/** Stable URL slugs for elektrik offers — order matches ELEKTRIK_PRICES groups/items */
export const ELEKTRIK_OFFER_SLUGS = [
  "ustanovka-rozetki-otkrytaya-provodka",
  "ustanovka-rozetki-skrytaya-provodka",
  "ustanovka-vyklyuchatelya",
  "ustanovka-prohodnogo-vyklyuchatelya",
  "blok-rozetok-kuhnya-vannaya",
  "ustanovka-rozetki-elektroplity-220v",
  "ustanovka-rozetki-elektroplity-380v",
  "ustanovka-podrozetnika",
  "kommunikatsiya-soedinitelnoy-korobki",
  "ustanovka-zvonka",
  "ustanovka-termoregulyatora-teplogo-pola",
  "sborka-lyustry",
  "ustanovka-lyustry",
  "ustanovka-lyustry-4-rozhka",
  "ustanovka-nestandartnoy-lyustry",
  "ustanovka-svetilnika",
  "ustanovka-tochechnogo-svetilnika",
  "ustanovka-svetilnika-armstrong",
  "montazh-led-lenty",
  "montazh-profilya-led-lenty",
  "montazh-shinoprovoda",
  "ustanovka-avtomata-1-polyus",
  "ustanovka-avtomata-2-polyusa-uzo",
  "ustanovka-avtomata-3-polyusa",
  "montazh-elektroshchita-12-moduley",
  "montazh-elektroshchita-18-moduley",
  "montazh-elektroshchita-24-moduley",
  "montazh-elektroshchita-36-moduley",
  "ustroystvo-nishi-pod-elektroshchit",
  "ustanovka-elektroschetchika",
  "demontazh-elektroschetchika",
  "prokladka-kabelya",
  "prokladka-kabelya-v-gofre",
  "montazh-kabel-kanala",
  "shtroblenie-kirpichnoy-steny",
  "shtroblenie-betonnoy-steny",
  "sverlenie-pod-rozetnik",
  "diagnostika-elektroseti",
  "poisk-neispravnosti-provodki",
  "ustanovka-teplogo-pola",
  "montazh-videonablyudeniya",
  "demontazh-rozetki-ili-vyklyuchatelya",
  "demontazh-lyustry-ili-svetilnika",
  "demontazh-avtomata-v-shchite",
  "demontazh-elektroshchita",
] as const;

/** Stable URL slugs for santehnik offers — order matches SANTEHNIK_PRICES groups/items */
export const SANTEHNIK_OFFER_SLUGS = [
  "ustanovka-smesitelya-otechestvennyy",
  "ustanovka-smesitelya-importnyy",
  "ustanovka-smesitelya-s-termoregulyatorom",
  "ustanovka-gigienicheskogo-dusha",
  "zamena-kartridzha-ili-prokladki",
  "ustanovka-ekscentrikov",
  "demontazh-smesitelya",
  "ustanovka-unitaza",
  "ustanovka-podvesnogo-unitaza",
  "ustanovka-bide-ili-pissuara",
  "ustanovka-installyatsii",
  "ustanovka-gofry-na-unitaz",
  "ustanovka-sololifta",
  "remont-armatury-bachka",
  "ustanovka-gibkoy-podvodki",
  "demontazh-unitaza",
  "ustanovka-akrilovoy-vanny",
  "ustanovka-vanny-s-gidromassazhem",
  "ustanovka-dushevoy-kabiny",
  "ustanovka-dushevogo-poddona",
  "ustanovka-obvyazki-dlya-vanny",
  "ustanovka-donnogo-klapana",
  "ustanovka-ekrana-pod-vannu",
  "germetizatsiya-vanny-ili-dushevoy",
  "demontazh-vanny",
  "ustanovka-rakoviny",
  "ustanovka-rakoviny-tyulpan",
  "ustanovka-rakoviny-moydodyr",
  "ustanovka-sifona",
  "ustanovka-metallicheskogo-sifona",
  "demontazh-rakoviny",
  "ustranenie-zasora",
  "ustranenie-zasora-khimicheskiy-sposob",
  "ustranenie-zasora-s-razborom-trub",
  "ustranenie-zasora-elektromehanicheskiy",
  "ustranenie-zasora-gidrodinamicheskiy",
  "prochistka-kanalizatsii",
  "ustranenie-protechki",
  "remont-trub-i-stoyakov",
  "razvodka-trub",
  "montazh-vodorozetki",
  "montazh-baypasa",
  "ustanovka-sharovogo-krana",
  "ustanovka-obratnogo-klapana",
  "ustanovka-reduktora-davleniya",
  "ustanovka-kollektora",
  "ustanovka-schetchika-vody",
  "opressovka-sistemy-otopleniya",
  "ustanovka-vodonagrevatelya-do-50-l",
  "ustanovka-vodonagrevatelya-svyshe-50-l",
  "podklyuchenie-protochnogo-vodonagrevatelya",
  "ustanovka-filtra-dlya-vody",
] as const;

/** Stable URL slugs for master-na-chas offers — order matches MASTER_PRICES groups/items */
export const MASTER_NA_CHAS_OFFER_SLUGS = [
  "sborka-mebeli",
  "sborka-kuhonnogo-garnitura",
  "sborka-shkafa-kupe",
  "sborka-tumby-pod-rakovinu",
  "ustanovka-karniza-ili-gardin",
  "ustanovka-polok-i-zerkal",
  "kreplenie-predmetov-interera",
  "ustanovka-zamka",
  "zamena-dvernoy-ruchki",
  "regulirovka-dveri",
  "ustanovka-dovodchika",
  "podklyuchenie-varochnoy-paneli",
  "ustanovka-varochnoy-poverhnosti",
  "podklyuchenie-duhovogo-shkafa",
  "ustanovka-duhovogo-shkafa",
  "podklyuchenie-posudomoechnoy-mashiny",
  "ustanovka-vytyazhki",
  "ustanovka-vozduhootvoda-gofra",
  "ustanovka-vozduhootvoda-korob",
  "ustanovka-vstroennogo-holodilnika",
  "ustanovka-kanalnogo-ventilyatora",
  "demontazh-posudomoechnoy-mashiny",
  "demontazh-vytyazhki",
  "kreplenie-televizora-na-stenu",
  "podklyuchenie-televizora",
  "podklyuchenie-stiralnoy-mashiny",
  "ustanovka-stiralnoy-mashiny",
  "ustanovka-vodonagrevatelya",
  "demontazh-stiralnoy-mashiny",
  "demontazh-boylera",
  "ustanovka-polotentsesushitelya",
  "perenos-polotentsesushitelya",
  "demontazh-polotentsesushitelya",
  "ustanovka-radiatora-otopleniya",
  "demontazh-radiatora-otopleniya",
  "sverlenie-otverstiy",
  "germetizatsiya-shvov",
  "zamena-smesitelya",
  "zamena-rozetki-ili-vyklyuchatelya",
  "ustanovka-lyustry-ili-svetilnika",
  "pomoshch-posle-pereezda",
  "pochasovaya-oplata-mastera",
  "minimalnyy-vyzov-mastera",
] as const;

/** Stable URL slugs for remont-kvartir offers — order matches REMONT_PRICES groups/items */
export const REMONT_KVARTIR_OFFER_SLUGS = [
  "kosmeticheskiy-remont",
  "kapitalnyy-remont",
  "remont-pod-klyuch",
  "remont-vannoy-komnaty",
  "remont-kuhni",
  "remont-komnaty",
  "remont-gostinoy",
  "remont-spalni",
  "remont-prihozhey",
  "remont-balkona",
  "remont-novostroyki",
  "remont-odnokomnatnoy-kvartiry",
] as const;

/** Old remont offer URLs → category hub */
export const REMONT_KVARTIR_LEGACY_OFFER_REDIRECTS = [
  "shtroblenie-pod-provodku-kirpich",
  "shtroblenie-pod-provodku-beton",
  "shtroblenie-pod-truby",
  "sverlenie-otverstiy-v-betone",
  "pokleyka-oboev",
  "ukladka-plitki",
  "montazh-natyazhnogo-potolka",
] as const;

/** Old nested santehnik URLs → /master-na-chas/[slug] */
export const SANTEHNIK_TO_MASTER_OFFER_REDIRECTS = [
  "podklyuchenie-stiralnoy-mashiny",
  "podklyuchenie-posudomoechnoy-mashiny",
  "ustanovka-vytyazhki",
  "sborka-tumby-pod-rakovinu",
  "ustanovka-polotentsesushitelya",
  "ustanovka-radiatora-otopleniya",
] as const;

/** Old nested elektrik URLs → /master-na-chas/[destinationSlug] */
export const ELEKTRIK_TO_MASTER_OFFER_REDIRECTS: Record<string, string> = {
  "podklyuchenie-varochnoy-paneli": "podklyuchenie-varochnoy-paneli",
  "ustanovka-varochnoy-poverhnosti": "ustanovka-varochnoy-poverhnosti",
  "podklyuchenie-duhovogo-shkafa": "podklyuchenie-duhovogo-shkafa",
  "ustanovka-duhovogo-shkafa": "ustanovka-duhovogo-shkafa",
  "podklyuchenie-stiralnoy-mashiny-elektrik": "podklyuchenie-stiralnoy-mashiny",
  "ustanovka-kanalnogo-ventilyatora": "ustanovka-kanalnogo-ventilyatora",
  "kreplenie-televizora-na-stenu": "kreplenie-televizora-na-stenu",
};

/** Legacy flat URLs → new nested paths under /santehnik/ */
export const SANTEHNIK_LEGACY_REDIRECTS: Record<string, string> = {
  "zamena-smesitelya": "ustanovka-smesitelya-otechestvennyy",
  "ustanovka-vanny": "ustanovka-akrilovoy-vanny",
  "ustanovka-bojlera": "ustanovka-vodonagrevatelya-do-50-l",
  "zamena-trub": "razvodka-trub",
  "ustranenie-zasora": "ustranenie-zasora",
  "ustanovka-unitaza": "ustanovka-unitaza",
  "ustanovka-rakoviny": "ustanovka-rakoviny",
  "ustanovka-dushevoy-kabiny": "ustanovka-dushevoy-kabiny",
};

/** Legacy flat URLs → new nested paths under /elektrik/ */
export const ELEKTRIK_LEGACY_REDIRECTS: Record<string, string> = {
  "ustanovka-rozetok": "ustanovka-rozetki-skrytaya-provodka",
  "ustanovka-vyklyuchateley": "ustanovka-vyklyuchatelya",
  "ustanovka-lyustry": "ustanovka-lyustry",
  "zamena-avtomata": "ustanovka-avtomata-1-polyus",
  "zamena-provodki": "prokladka-kabelya",
  "poisk-kz": "poisk-neispravnosti-provodki",
};
