/** Stable URL slugs for elektrik offers — order matches ELEKTRIK_PRICES groups/items */
export const ELEKTRIK_OFFER_SLUGS = [
  "ustanovka-rozetki-otkrytaya-provodka",
  "ustanovka-rozetki-skrytaya-provodka",
  "ustanovka-vyklyuchatelya",
  "blok-rozetok-kuhnya-vannaya",
  "ustanovka-zvonka",
  "ustanovka-termoregulyatora-teplogo-pola",
  "sborka-lyustry",
  "ustanovka-lyustry",
  "ustanovka-svetilnika",
  "ustanovka-tochechnogo-svetilnika",
  "montazh-led-lenty",
  "montazh-profilya-led-lenty",
  "ustanovka-avtomata-1-polyus",
  "ustanovka-avtomata-2-polyusa-uzo",
  "ustanovka-avtomata-3-polyusa",
  "montazh-elektroshchita-12-moduley",
  "montazh-elektroshchita-24-moduley",
  "ustanovka-elektroschetchika",
  "prokladka-kabelya",
  "prokladka-kabelya-v-gofre",
  "montazh-kabel-kanala",
  "shtroblenie-kirpichnoy-steny",
  "shtroblenie-betonnoy-steny",
  "sverlenie-pod-rozetnik",
  "demontazh-rozetki-ili-vyklyuchatelya",
  "demontazh-lyustry-ili-svetilnika",
  "demontazh-avtomata-v-shchite",
  "demontazh-elektroshchita",
  "podklyuchenie-varochnoy-paneli",
  "podklyuchenie-duhovogo-shkafa",
  "podklyuchenie-stiralnoy-mashiny-elektrik",
  "kreplenie-televizora-na-stenu",
  "diagnostika-elektroseti",
  "poisk-neispravnosti-provodki",
  "montazh-videonablyudeniya",
  "ustanovka-teplogo-pola",
] as const;

/** Stable URL slugs for santehnik offers — order matches SANTEHNIK_PRICES groups/items */
export const SANTEHNIK_OFFER_SLUGS = [
  "ustanovka-smesitelya-otechestvennyy",
  "ustanovka-smesitelya-importnyy",
  "ustanovka-smesitelya-s-termoregulyatorom",
  "ustanovka-gigienicheskogo-dusha",
  "zamena-kartridzha-ili-prokladki",
  "ustanovka-ekscentrikov",
  "ustanovka-unitaza",
  "ustanovka-podvesnogo-unitaza",
  "ustanovka-bide-ili-pissuara",
  "ustanovka-installyatsii",
  "remont-armatury-bachka",
  "ustanovka-gibkoy-podvodki",
  "ustanovka-akrilovoy-vanny",
  "ustanovka-vanny-s-gidromassazhem",
  "ustanovka-dushevoy-kabiny",
  "ustanovka-dushevogo-poddona",
  "germetizatsiya-vanny-ili-dushevoy",
  "ustanovka-ekrana-pod-vannu",
  "ustanovka-rakoviny",
  "ustanovka-rakoviny-tyulpan",
  "sborka-tumby-pod-rakovinu",
  "ustanovka-sifona",
  "ustanovka-metallicheskogo-sifona",
  "ustranenie-zasora",
  "ustranenie-zasora-khimicheskiy-sposob",
  "ustranenie-protechki",
  "remont-trub-i-stoyakov",
  "ustanovka-polotentsesushitelya",
  "montazh-baypasa",
  "ustanovka-radiatora-otopleniya",
  "ustanovka-sharovogo-krana",
  "ustanovka-schetchika-vody",
  "razvodka-trub",
  "ustanovka-vodonagrevatelya-do-50-l",
  "ustanovka-vodonagrevatelya-svyshe-50-l",
  "podklyuchenie-stiralnoy-mashiny",
  "podklyuchenie-posudomoechnoy-mashiny",
  "ustanovka-vytyazhki",
  "ustanovka-filtra-dlya-vody",
  "prochistka-kanalizatsii",
] as const;

/** Legacy flat URLs → new nested paths under /santehnik/ */
export const SANTEHNIK_LEGACY_REDIRECTS: Record<string, string> = {
  "zamena-smesitelya": "ustanovka-smesitelya-otechestvennyy",
  "ustanovka-vanny": "ustanovka-akrilovoy-vanny",
  "ustanovka-bojlera": "ustanovka-vodonagrevatelya-do-50-l",
  "zamena-trub": "razvodka-trub",
  "ustranenie-zasora": "ustranenie-zasora",
  "ustanovka-unitaza": "ustanovka-unitaza",
  "ustanovka-rakoviny": "ustanovka-rakoviny",
  "ustanovka-dushevoy-kabiny": "ustanovka-dushevoy-kabiny",
};

/** Legacy flat URLs → new nested paths under /elektrik/ */
export const ELEKTRIK_LEGACY_REDIRECTS: Record<string, string> = {
  "ustanovka-rozetok": "ustanovka-rozetki-skrytaya-provodka",
  "ustanovka-vyklyuchateley": "ustanovka-vyklyuchatelya",
  "ustanovka-lyustry": "ustanovka-lyustry",
  "zamena-avtomata": "ustanovka-avtomata-1-polyus",
  "zamena-provodki": "prokladka-kabelya",
  "poisk-kz": "poisk-neispravnosti-provodki",
};
