/** Stable URL slugs for elektrik offers — order matches ELEKTRIK_PRICES groups/items */
export const ELEKTRIK_OFFER_SLUGS = [
  "ustanovka-rozetki-otkrytaya-provodka",
  "ustanovka-rozetki-skrytaya-provodka",
  "ustanovka-vyklyuchatelya",
  "blok-rozetok-kuhnya-vannaya",
  "ustanovka-zvonka",
  "ustanovka-termoregulyatora-teplogo-pola",
  "sborka-lyustry",
  "ustanovka-lyustry",
  "ustanovka-svetilnika",
  "ustanovka-tochechnogo-svetilnika",
  "montazh-led-lenty",
  "montazh-profilya-led-lenty",
  "ustanovka-avtomata-1-polyus",
  "ustanovka-avtomata-2-polyusa-uzo",
  "ustanovka-avtomata-3-polyusa",
  "montazh-elektroshchita-12-moduley",
  "montazh-elektroshchita-24-moduley",
  "ustanovka-elektroschetchika",
  "prokladka-kabelya",
  "prokladka-kabelya-v-gofre",
  "montazh-kabel-kanala",
  "shtroblenie-kirpichnoy-steny",
  "shtroblenie-betonnoy-steny",
  "sverlenie-pod-rozetnik",
  "demontazh-rozetki-ili-vyklyuchatelya",
  "demontazh-lyustry-ili-svetilnika",
  "demontazh-avtomata-v-shchite",
  "demontazh-elektroshchita",
  "podklyuchenie-varochnoy-paneli",
  "podklyuchenie-duhovogo-shkafa",
  "podklyuchenie-stiralnoy-mashiny-elektrik",
  "kreplenie-televizora-na-stenu",
  "diagnostika-elektroseti",
  "poisk-neispravnosti-provodki",
  "montazh-videonablyudeniya",
  "ustanovka-teplogo-pola",
] as const;

/** Legacy flat URLs → new nested paths under /elektrik/ */
export const ELEKTRIK_LEGACY_REDIRECTS: Record<string, string> = {
  "ustanovka-rozetok": "ustanovka-rozetki-skrytaya-provodka",
  "ustanovka-vyklyuchateley": "ustanovka-vyklyuchatelya",
  "ustanovka-lyustry": "ustanovka-lyustry",
  "zamena-avtomata": "ustanovka-avtomata-1-polyus",
  "zamena-provodki": "prokladka-kabelya",
  "poisk-kz": "poisk-neispravnosti-provodki",
};
